const products = [
  {
    id: 1,
    first_name: "Fairfax",
    last_name: "Daws",
    email: "fdaws0@redcross.org",
    gender: "Male",
    ip_address: "74.126.209.216",
  },
  {
    id: 2,
    first_name: "Gwenore",
    last_name: "Fronczak",
    email: "gfronczak1@youtube.com",
    gender: "Female",
    ip_address: "74.7.8.132",
  },
  {
    id: 3,
    first_name: "Agna",
    last_name: "Dmtrovic",
    email: "admtrovic2@ucla.edu",
    gender: "Polygender",
    ip_address: "24.71.111.127",
  },
  {
    id: 4,
    first_name: "Rikki",
    last_name: "Huikerby",
    email: "rhuikerby3@cmu.edu",
    gender: "Male",
    ip_address: "42.185.247.27",
  },
  {
    id: 5,
    first_name: "Alysa",
    last_name: "Vanderplas",
    email: "avanderplas4@drupal.org",
    gender: "Female",
    ip_address: "197.82.222.171",
  },
  {
    id: 6,
    first_name: "Gipsy",
    last_name: "Briereton",
    email: "gbriereton5@sitemeter.com",
    gender: "Female",
    ip_address: "56.197.10.210",
  },
  {
    id: 7,
    first_name: "Norrie",
    last_name: "Teggin",
    email: "nteggin6@google.com.hk",
    gender: "Female",
    ip_address: "36.92.165.87",
  },
  {
    id: 8,
    first_name: "Nanci",
    last_name: "Insoll",
    email: "ninsoll7@google.nl",
    gender: "Female",
    ip_address: "7.82.223.209",
  },
  {
    id: 9,
    first_name: "Janenna",
    last_name: "Couchman",
    email: "jcouchman8@creativecommons.org",
    gender: "Female",
    ip_address: "239.115.177.61",
  },
  {
    id: 10,
    first_name: "Nobie",
    last_name: "Thurlby",
    email: "nthurlby9@senate.gov",
    gender: "Male",
    ip_address: "143.239.144.202",
  },
];

module.exports = { products };
